### ISSUE TITLE
"Something went wrong ..." error message before searching

### ISSUE THREAD

**Issue by jbampton** [Andrew-Colman/image-fetch#24]
<img width="719" alt="Screen Shot 2020-12-31 at 3 41 23 pm" src="https://user-images.githubusercontent.com/418747/103396450-17f82400-4b7f-11eb-9e53-cbbf144b63fb.png">

**Comment by jbampton** [comment]
Only seems to show up when my PR was deployed here -> https://image-fetch-git-fork-jbampton-update-editorconfig.spectralapps.vercel.app/

**Comment by Andrew-Colman** [comment]
@jbampton 
it's strange that vercel isn't loading the api key secret from environment-variables when preview urls

**Comment by Andrew-Colman** [comment]
@jbampton  I fixed it moments ago for my own preview deploys, that was showing "Something went wrong ..." (because doesn't loaded api key) 

but now for others PR is having this issue 🤔

**Comment by Andrew-Colman** [comment]
I can't find a solution at vercel docs, so I think i'll make github actions populate a preview api key at PR's

**Comment by Andrew-Colman** [comment]
@jbampton I found the issue, the issue is on the framework that I'm using ( create-react-app)

this framework can only read env variables with this prefix REACT_APP_(env_name)

so in the preview url its looking for a API_KEY env variable that the framework can't understand 

added it at dashboard for remote previews urls 

for local  preview .env file is required
